
name: Auto Generate AI Blog Post

on:
  schedule:
    # - cron: '0 6 * * *'   # Every day at 06:00 UTC
    - cron: '*/10 * * * *'  # Example: every 30 min (avoid spamming every 3 min)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Setup Git identity
        run: |
          git config --global user.name "Kunal-ghosh"
          git config --global user.email "kunalghosh5135@gmail.com"

      - name: Debug file tree
        run: |
          set -e
          CANDIDATES=("pages/utils/generatePost.js" "utils/generatePost.js" "pages/generatePost.js" "scripts/generatePost.js")
          FOUND=""
          for p in "${CANDIDATES[@]}"; do
            if [ -f "$p" ]; then FOUND="$p"; break; fi
          done
          if [ -z "$FOUND" ]; then
            echo "❌ generatePost.js not found. Checked: ${CANDIDATES[*]}"
            echo "Current tree:"
            ls -R
            exit 1
          fi
          echo "✅ Using $FOUND"
          node "$FOUND"


      - name: Generate AI Post
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: node utils/generatePost.js

      - name: Show generated posts
        run: |
          echo "Files in pages/posts:"
          ls -la pages/posts

      - name: Print latest generated post
        run: |
          FILE=$(ls -t pages/posts/*.js | head -n1)
          echo "✅ Latest generated file: $FILE"
          echo "---- FILE CONTENT ----"
          cat "$FILE"
          echo "----------------------"

      - name: Commit generated post (to main)
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add pages/posts
          git commit -m "Add auto-generated post" || echo "No changes"
          # Use PAT token to allow triggering other workflows
          if [ -n "$PAT_TOKEN" ]; then
            git remote set-url origin "https://x-access-token:$PAT_TOKEN@github.com/${{ github.repository }}.git"
          else
            git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          fi
          git push origin HEAD:main
      # Note: No manual deployment needed here
      # The deploy.yml workflow will automatically trigger when we push to main
