name: Auto Generate AI Blog Post

on:
  schedule:
    # - cron: '0 6 * * *' # Every day at 6:00 UTC
    - cron: '*/3 * * * *'
  workflow_dispatch:   # Allows manual trigger

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup Git identity
        run: |
          git config --global user.name "Kunal-ghosh"
          git config --global user.email "kunalghosh5135@gmail.com"

      - name: Generate new post
        run: node utils/generatePost.js

      - name: Deploy to GitHub Pages
        run: npm run deploy

      - name: Commit generated post
        run: |
          git config user.name "Kunal-ghosh"
          git config user.email "kunalghosh5135@gmail.com"
          git add pages/posts
          git commit -m "Add auto-generated post [skip ci]" || echo "No changes"
          git push origin main

      - name: Generate AI Post
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: node utils/generatePost.js
