name: Test Trigger on Push

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test if workflow triggers
        run: |
          echo "✅ Workflow triggered successfully!"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
